// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqtbI62DSR0a-FIdbTvKS4QLsyMoSl5Mk',
    appId: '1:254409714237:web:ae0a4dce33caccd3219854',
    messagingSenderId: '254409714237',
    projectId: 'copedu-1585a',
    authDomain: 'copedu-1585a.firebaseapp.com',
    storageBucket: 'copedu-1585a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22UWIh0W23VP8mLfK7IjHU3RTI_p8HgQ',
    appId: '1:254409714237:android:08a28d6ab2d705f6219854',
    messagingSenderId: '254409714237',
    projectId: 'copedu-1585a',
    storageBucket: 'copedu-1585a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGKBalVYXmsVZy-Ma0gOdtMdoCGvMZrEA',
    appId: '1:254409714237:ios:2cc7d2a0bc7ce4cd219854',
    messagingSenderId: '254409714237',
    projectId: 'copedu-1585a',
    storageBucket: 'copedu-1585a.firebasestorage.app',
    iosBundleId: 'com.ptoo.copedu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGKBalVYXmsVZy-Ma0gOdtMdoCGvMZrEA',
    appId: '1:254409714237:ios:2cc7d2a0bc7ce4cd219854',
    messagingSenderId: '254409714237',
    projectId: 'copedu-1585a',
    storageBucket: 'copedu-1585a.firebasestorage.app',
    iosBundleId: 'com.ptoo.copedu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqtbI62DSR0a-FIdbTvKS4QLsyMoSl5Mk',
    appId: '1:254409714237:web:a4a80a188f10d61b219854',
    messagingSenderId: '254409714237',
    projectId: 'copedu-1585a',
    authDomain: 'copedu-1585a.firebaseapp.com',
    storageBucket: 'copedu-1585a.firebasestorage.app',
  );
}
