# ios/Podfile

platform :ios, '15.0'

# Ścieżka do Fluttera
flutter_root = File.expand_path(File.join('..', 'flutter'))

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  # Wymagane przy nowym Firebase i wielu pluginach Swift
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # (Opcjonalnie) przydatne przy dystrybucji binariów
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
